#!/bin/bash
set -e

# make sure OpenHIM service is started
sleep 10

cd /usr/share/openhim-mediator-mhero

# fetch server details
. /usr/share/debconf/confmodule
db_get openhim-config/protocol
PROTOCOL=$RET
db_get openhim-config/host
HOST=$RET
db_get openhim-config/port
PORT=$RET
db_get openhim-config/username
USER=$RET
db_get openhim-config/password
PASSWD=$RET

echo "Configured for OpenHIM server $PROTOCOL://$HOST:$PORT using user $USER"

# inject server details
sudo sed -i -r 's/"username": ".*"/"username": "'$USER'"/' config/config.json
sudo sed -i -r 's/"password": ".*"/"password": "'$PASSWD'"/' config/config.json
sudo sed -i -r 's/"apiURL": ".*"/"apiURL": "'$PROTOCOL':\/\/'$HOST:$PORT'"/' config/config.json

sudo -u openhim /bin/bash /etc/openhim/install_node_4.sh

chown -R openhim:openhim /usr/share/openhim-mediator-mhero

stop openhim-mediator-mhero || true
start openhim-mediator-mhero || true
