#!/bin/bash
set -e

# make sure OpenHIM service is started
sleep 10

cd /usr/share/openhim-mediator-mhero

# fetch server details
. /usr/share/debconf/confmodule
db_get openhim-config/host
HOST=$RET
db_get openhim-config/port
PORT=$RET
db_get openhim-config/username
USER=$RET
db_get openhim-config/password
PASSWD=$RET

echo "Configured for OpenHIM server $HOST:$PORT using user $USER"

# inject server details
sudo sed -i -r 's/"username": ".*"/"username": "'$USER'"/' config/config.json
sudo sed -i -r 's/"password": ".*"/"password": "'$PASSWD'"/' config/config.json
sudo sed -i -r 's/"apiURL": ".*"/"apiURL": "'$HOST:$PORT'"/' config/config.json

# inject server to mediator config
# sudo sed -i -r 's/root@openhim.org/'$USER'/' config/config.json
# sudo sed -i -r 's/password/'$PASSWD'/' config/config.json
# sudo sed -i -r 's/localhost:8080/'$HOST:$PORT'/' config/config.json

stop openhim-mediator-mhero || true
start openhim-mediator-mhero || true
